version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - express-api
      - whoami

  express-api:
    build:
      context: ./server
    container_name: express-api
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  whoami:
    image: traefik/whoami
    container_name: whoami

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
