https://fakestoreapi.com/products
https://fakestoreapi.com/
https://dummyjson.com/docs/image
https://dummyjson.com/products
https://dummyjson.com/products
https://fakeapi.platzi.com/en/rest/auth-jwt/
https://dummyjson.com/
https://dummyjson.com/users


✅ All CRUD Operations
✅ REST API
✅ GraphQL
✅ Pagination
✅ Auth with JWT
✅ Upload Files
✅ Filter products by category, title and price range
✅ Create users and check to see if they already exist
✅ Postman and Insomnia files
✅ Product images generated by AI
[GET] https://api.escuelajs.co/api/v1/auth/profile