| ✅ **Capability**                                             | 💡 **Description**                                 | 🧪 **MongoDB Shell Syntax Example**                                                                                                                |
| ------------------------------------------------------------ | -------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔍 **Search / Filter** (`$match`)                            | Filters documents like `.find()`                   | `{ $match: { age: { $gt: 25 } } }`                                                                                                                 |
| 🎯 **Field Selection** (`$project`)                          | Include/exclude/rename fields                      | `{ $project: { name: 1, _id: 0 } }`                                                                                                                |
| 📊 **Grouping & Aggregation** (`$group`)                     | Group and calculate aggregates                     | `{ $group: { _id: "$city", total: { $sum: "$amount" } } }`                                                                                         |
| 📌 **Sorting** (`$sort`)                                     | Sorts documents by fields                          | `{ $sort: { age: -1 } }`                                                                                                                           |
| ⏩ **Pagination** (`$skip`, `$limit`)                         | Skip and limit documents                           | `{ $skip: 10 }, { $limit: 5 }`                                                                                                                     |
| 🔁 **Unwind Arrays** (`$unwind`)                             | Breaks arrays into multiple documents              | `{ $unwind: "$hobbies" }`                                                                                                                          |
| 🔗 **Join Other Collections** (`$lookup`)                    | Joins with another collection (like SQL JOIN)      | `{ $lookup: { from: "orders", localField: "userId", foreignField: "_id", as: "orders" } }`                                                         |
| 🧩 **Reshape Documents** (`$set`, `$addFields`, `$unset`)    | Add/remove fields dynamically                      | `{ $set: { fullName: "$firstName $lastName" } }`                                                                                                   |
| 🧮 **Counting** (`$count`)                                   | Count documents                                    | `{ $count: "total" }`                                                                                                                              |
| 🧠 **Custom Calculations** (`$accumulator`, `$function`)     | JavaScript-style custom functions                  | `{ $group: { _id: null, total: { $accumulator: { init: "...", accumulate: "...", ... } } } }`                                                      |
| 📚 **Categorize Data** (`$bucket`, `$bucketAuto`)            | Group into numeric/date ranges                     | `{ $bucket: { groupBy: "$age", boundaries: [0, 20, 40, 60], default: "Others", output: { count: { $sum: 1 } } } }`                                 |
| 🎛️ **Multiple Pipelines** (`$facet`)                        | Run multiple pipelines in parallel                 | `{ $facet: { stats: [...], topUsers: [...] } }`                                                                                                    |
| 🔃 **Document Replacement** (`$replaceRoot`, `$replaceWith`) | Replace whole document                             | `{ $replaceRoot: { newRoot: "$details" } }`                                                                                                        |
| 🧭 **Geospatial Aggregation** (`$geoNear`)                   | Nearby location-based aggregation                  | `{ $geoNear: { near: [x, y], distanceField: "dist.calculated", spherical: true } }`                                                                |
| 🪜 **Recursive Lookup** (`$graphLookup`)                     | Recursive relationships (e.g., trees, hierarchies) | `{ $graphLookup: { from: "employees", startWith: "$managerId", connectFromField: "managerId", connectToField: "_id", as: "reportingHierarchy" } }` |
| 🔄 **Window Functions**                                      | Row-based computations                             | `{ $setWindowFields: { partitionBy: "$dept", sortBy: { age: 1 }, output: { rank: { $rank: {} } } } }`                                              |
| 🧾 **Text Transformations**                                  | Text manipulation operations                       | `{ $project: { nameLower: { $toLower: "$name" } } }`                                                                                               |
| 🧪 **Write Output to Collection** (`$merge`, `$out`)         | Save pipeline result to a collection               | `{ $merge: { into: "summary" } }` or `{ $out: "archived" }`                                                                                        |
| 🛡️ **Redact / Security Filtering** (`$redact`)              | Mask/hide parts of document conditionally          | `{ $redact: { $cond: [ <condition>, "$$DESCEND", "$$PRUNE" ] } }`                                                                                  |
